resources:  
  repositories:
    - repository: templates
      type: git
      name: devops.pipelinetemplates
pool:
  name: Default
steps:
- template: shared/dotnet-build.yml@templates
  parameters:
    projects: '**/*.csproj'
    restoreNuGet: true
    solution: '**/*.sln'
    nugetConfigPath: 'nuget.config'
- template: windows/dotnet-test.yml@templates
  parameters:
    sourceDirectory: '$(Build.SourcesDirectory)'
    minCoverage: 45
- template: shared/dotnet-pack.yml@templates
  parameters:
    srcFolder: ''
    packages: ['Consul']  
