resources:  
  repositories:
    - repository: templates
      type: git
      name: devops.pipelinetemplates
pool:
  name: Hosted Ubuntu 1604
steps:
- template: shared/dotnet-build.yml@templates
  parameters:    
    mixedSolution: false
    nugetConfigPath: ''
- template: linux/dotnet-test.yml@templates
  parameters:    
    minCoverage: 10
    runIntegrationTestOnMasterOnly: false
- template: shared/dotnet-pack.yml@templates
  parameters:    
    packages: ['Consul']